### ISSUE TITLE
deepin-image-viewer crashes on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/deepin-image-viewer#49]
```
hillwood@linux-ibzl:~> deepin-image-viewer
段错误 (核心已转储)
hillwood@linux-ibzl:~> gdb deepin-image-viewer
GNU gdb (GDB; openSUSE Tumbleweed) 8.3
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from deepin-image-viewer...
(No debugging symbols found in deepin-image-viewer)
(gdb) r
Starting program: /usr/bin/deepin-image-viewer 
Missing separate debuginfo for /lib64/ld-linux-x86-64.so.2
Try: zypper install -C "debuginfo(build-id)=61d4b8695bd3838dec3433832d4842666349c2ad"
Missing separate debuginfo for /usr/lib64/libspeex.so.1
Try: zypper install -C "debuginfo(build-id)=cde6361887519f249563c1268405ebdde9bdbf9f"
Missing separate debuginfo for /lib64/libc.so.6
Try: zypper install -C "debuginfo(build-id)=4884b60caecd671b2c2954c6305c5412fa176c8e"
Missing separate debuginfo for /usr/lib64/libfreeimage.so.3
Try: zypper install -C "debuginfo(build-id)=f99374a311089057540b16c07eaf486f40e170b8"
Missing separate debuginfo for /usr/lib64/libQt5Svg.so.5
Try: zypper install -C "debuginfo(build-id)=110d5566ab0de7fa61608a4c8a39e6cf2afbb9eb"
Missing separate debuginfo for /usr/lib64/libQt5PrintSupport.so.5
Try: zypper install -C "debuginfo(build-id)=e60ac851e4a8822a7c2b56b31204bb4b9fd686cc"
Missing separate debuginfo for /usr/lib64/libQt5Widgets.so.5
Try: zypper install -C "debuginfo(build-id)=247a93f709a7be15b13be42aa7cd6f3cada1ec49"
Missing separate debuginfo for /usr/lib64/libQt5Gui.so.5
Try: zypper install -C "debuginfo(build-id)=044b7023433e6ac0495ffb0a868f3acbf33d6f45"
Missing separate debuginfo for /usr/lib64/libQt5DBus.so.5
Try: zypper install -C "debuginfo(build-id)=c4015bb5d6484a8cad625013d38515d97ff89a3d"
Missing separate debuginfo for /usr/lib64/libQt5Core.so.5
Try: zypper install -C "debuginfo(build-id)=a4d2d35caf901db992f725a9357e0f49c58a5cce"
Missing separate debuginfo for /usr/lib64/libstdc++.so.6
Try: zypper install -C "debuginfo(build-id)=0b3fc3b7af40d5569333ef4d85e0e2a65344e532"
Missing separate debuginfo for /lib64/libm.so.6
Try: zypper install -C "debuginfo(build-id)=d003f377a3941d09075c932b6041a88d8d55d00b"
Missing separate debuginfo for /lib64/libgcc_s.so.1
Try: zypper install -C "debuginfo(build-id)=66c85f9a5c79259a72874f3459feb2329e88e77c"
Missing separate debuginfo for /usr/lib64/libjpeg.so.8
Try: zypper install -C "debuginfo(build-id)=040fe1d7142af72683f0f7db8e7e3c6f46f136f1"
Missing separate debuginfo for /usr/lib64/libjxrglue.so.0
Try: zypper install -C "debuginfo(build-id)=0b6f7f2a1a1379936ea17bbdc7824ada830c8d87"
Missing separate debuginfo for /usr/lib64/libIlmImf-2_3.so.24
Try: zypper install -C "debuginfo(build-id)=365bba81d10cd9509dc338e756cb3992e125fc65"
Missing separate debuginfo for /usr/lib64/libHalf.so.24
Try: zypper install -C "debuginfo(build-id)=7535b9c9d87c88a42008588ee6049400d7b75f2c"
Missing separate debuginfo for /usr/lib64/libIex-2_3.so.24
Try: zypper install -C "debuginfo(build-id)=a8eddb8d3711af8fa690fcd62c4b726f87d14457"
Missing separate debuginfo for /lib64/libpthread.so.0
Try: zypper install -C "debuginfo(build-id)=d1e9eeb7a9bdf363e38d29c3b0fc27b9960a70e0"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /usr/lib64/libopenjp2.so.7
Try: zypper install -C "debuginfo(build-id)=e5af50344f1e2da0ec1bd7982aa0681291a04bca"
Missing separate debuginfo for /usr/lib64/libraw.so.19
Try: zypper install -C "debuginfo(build-id)=4b975cd10c35ea9c7aaf893d9329933d51f94fef"
Missing separate debuginfo for /usr/lib64/libpng16.so.16
Try: zypper install -C "debuginfo(build-id)=f4869f2e0bbb1f15050fb8349c5245de575c28a5"
Missing separate debuginfo for /usr/lib64/libtiff.so.5
Try: zypper install -C "debuginfo(build-id)=fbcaf1acecdc0680e967ecf9fc88f83d19e88e53"
Missing separate debuginfo for /usr/lib64/libwebpmux.so.3
Try: zypper install -C "debuginfo(build-id)=dd330bf724561ff2bbc5c072a5cee63483a7293a"
Missing separate debuginfo for /usr/lib64/libwebp.so.7
Try: zypper install -C "debuginfo(build-id)=3e877df3bf18bca96264b2b9bad381bcd43c2e89"
Missing separate debuginfo for /lib64/libz.so.1
Try: zypper install -C "debuginfo(build-id)=55df9c8d2e5b2996d155fa882e077dde2c8804c9"
Missing separate debuginfo for /usr/lib64/librsvg-2.so.2
Try: zypper install -C "debuginfo(build-id)=e8186b872f586ea1ae6ec17d078bc6343edc8e11"
Missing separate debuginfo for /usr/lib64/libgobject-2.0.so.0
Try: zypper install -C "debuginfo(build-id)=edba8f4bcbdff87a7b2fac8e47e63810a9924d4b"
Missing separate debuginfo for /usr/lib64/libglib-2.0.so.0
Try: zypper install -C "debuginfo(build-id)=ebf3acb924c951d97bb894908b8a70b66fdf71ec"
Missing separate debuginfo for /usr/lib64/libcairo.so.2
Try: zypper install -C "debuginfo(build-id)=883a57653dfbfcb2e6fefc503b948abe6a0a762d"
Missing separate debuginfo for /usr/lib64/libXext.so.6
Try: zypper install -C "debuginfo(build-id)=dca13fdc02949879bf45b39ffa8c1c3be1cadd66"
Missing separate debuginfo for /usr/lib64/libX11.so.6
Try: zypper install -C "debuginfo(build-id)=d9060a07622629726935ab3a8389e8e5be5d3d2e"
Missing separate debuginfo for /usr/lib64/libXi.so.6
Try: zypper install -C "debuginfo(build-id)=376e8af527b8553a4f0cc44bb313276ee4b4443c"
Missing separate debuginfo for /usr/lib64/libxcb-util.so.1
Try: zypper install -C "debuginfo(build-id)=881b0df32cd64d145e71d2a010daa172af7d7302"
Missing separate debuginfo for /usr/lib64/libxcb.so.1
Try: zypper install -C "debuginfo(build-id)=f8bba4e4411939ea7edef023a1b1ffb7b7220980"
Missing separate debuginfo for /usr/lib64/libstartup-notification-1.so.0
Try: zypper install -C "debuginfo(build-id)=b12b5a79160a7726468d0a6bc73776d19e94ec15"
Missing separate debuginfo for /usr/lib64/libQt5Multimedia.so.5
Try: zypper install -C "debuginfo(build-id)=de4c6b2cf389392dcf756aee657b95f047e0c2c8"
Missing separate debuginfo for /usr/lib64/libQt5X11Extras.so.5
Try: zypper install -C "debuginfo(build-id)=27e42af5286214231ec2238f526027c9af334053"
Missing separate debuginfo for /usr/lib64/libQt5Network.so.5
Try: zypper install -C "debuginfo(build-id)=ff2ed08b2d0a5de5572e64a41b9af89a2365888c"
Missing separate debuginfo for /usr/lib64/libQt5Xml.so.5
Try: zypper install -C "debuginfo(build-id)=568eafe722f96a63137b0744ac32718d015b3645"
Missing separate debuginfo for /usr/lib64/libGL.so.1
Try: zypper install -C "debuginfo(build-id)=f4d55f92a5c107683199350d65f493a3124b7210"
Missing separate debuginfo for /usr/lib64/libharfbuzz.so.0
Try: zypper install -C "debuginfo(build-id)=bb1ac0feff5cbeb7d2500bf85aaa2e4fc1da4cb4"
Missing separate debuginfo for /usr/lib64/libdbus-1.so.3
Try: zypper install -C "debuginfo(build-id)=120500bf3b32f4f10e3117fbff39c8d66d5377ba"
Missing separate debuginfo for /usr/lib64/libsystemd.so.0
Try: zypper install -C "debuginfo(build-id)=7694019aabca3d368ffbb56fdf508463863911ab"
Missing separate debuginfo for /usr/lib64/libicui18n.so.suse64.2
Try: zypper install -C "debuginfo(build-id)=4cc7b5e0018cd5f26fba43a53913b55298b5fd15"
Missing separate debuginfo for /usr/lib64/libicuuc.so.suse64.2
Try: zypper install -C "debuginfo(build-id)=b9d057fd9784aa7405fc914bd865eb3a8218386a"
Missing separate debuginfo for /lib64/libdl.so.2
Try: zypper install -C "debuginfo(build-id)=07df0db2a2e4008e0613d8f87a3db6c932bccb93"
Missing separate debuginfo for /usr/lib64/libpcre2-16.so.0
Try: zypper install -C "debuginfo(build-id)=f4136226f99005abc1307a5db863086d21172998"
Missing separate debuginfo for /usr/lib64/libdouble-conversion.so.2
Try: zypper install -C "debuginfo(build-id)=86ce4256e5f14790d05c2b97d5f5c4df84212e0d"
Missing separate debuginfo for /usr/lib64/libjpegxr.so.0
Try: zypper install -C "debuginfo(build-id)=7ebd6b3b6c6cde856669c7222d21e28909772d09"
Missing separate debuginfo for /usr/lib64/libIlmThread-2_3.so.24
Try: zypper install -C "debuginfo(build-id)=9376fa249a858b271b1bd6416736a18bcf66240a"
Missing separate debuginfo for /usr/lib64/libjasper.so.4
Try: zypper install -C "debuginfo(build-id)=2c5dfa452530b4eaa3ab4b92a62347e825029380"
Missing separate debuginfo for /usr/lib64/liblcms2.so.2
Try: zypper install -C "debuginfo(build-id)=9ccd0293169e1f020e582ed1ec06b5a36d95a641"
Missing separate debuginfo for /usr/lib64/libgomp.so.1
Try: zypper install -C "debuginfo(build-id)=280014844e3d37a6c586d27db0de75da9a6d1a77"
Missing separate debuginfo for /usr/lib64/liblzma.so.5
Try: zypper install -C "debuginfo(build-id)=0337cf89f7ad53c850481d718a93a5f0a9a2e2d2"
Missing separate debuginfo for /usr/lib64/libjbig.so.2
Try: zypper install -C "debuginfo(build-id)=c5780428cd600bcc5af36c39caf2c08743a2be8f"
Missing separate debuginfo for /usr/lib64/libgio-2.0.so.0
Try: zypper install -C "debuginfo(build-id)=1872ef001780bceb3710332c05487a351a2dccb5"
Missing separate debuginfo for /usr/lib64/libgdk_pixbuf-2.0.so.0
Try: zypper install -C "debuginfo(build-id)=03b14a21a01a8604d8ced049e64f094c879f2fdd"
Missing separate debuginfo for /usr/lib64/libpangocairo-1.0.so.0
Try: zypper install -C "debuginfo(build-id)=ff573256c0ddce892d4674936c9951f9f0137353"
Missing separate debuginfo for /usr/lib64/libpango-1.0.so.0
Try: zypper install -C "debuginfo(build-id)=6f5438612a1cc7848e43045e4d59805f46ab85d0"
Missing separate debuginfo for /usr/lib64/libcroco-0.6.so.3
Try: zypper install -C "debuginfo(build-id)=b6cfaeb603adb38171d174dc23d6559510809588"
Missing separate debuginfo for /usr/lib64/libpangoft2-1.0.so.0
Try: zypper install -C "debuginfo(build-id)=278a37aa6338df365565b3afe4332e10568dbb29"
Missing separate debuginfo for /usr/lib64/libfontconfig.so.1
Try: zypper install -C "debuginfo(build-id)=c001f10117b364f192379d032bfe34dd1e2a46a5"
Missing separate debuginfo for /usr/lib64/libxml2.so.2
Try: zypper install -C "debuginfo(build-id)=c4bcd882b8658cc4eae582b91829874db6bcecd5"
Missing separate debuginfo for /usr/lib64/libffi.so.7
Try: zypper install -C "debuginfo(build-id)=0984e3e2665fadf299a3074d61009a531867aa52"
Missing separate debuginfo for /usr/lib64/libpcre.so.1
Try: zypper install -C "debuginfo(build-id)=237707498df7a4bead4494f30da1c665146b1c19"
Missing separate debuginfo for /usr/lib64/libpixman-1.so.0
Try: zypper install -C "debuginfo(build-id)=b3d38e5860c48e59aae56c814517e6d556ef15e7"
Missing separate debuginfo for /usr/lib64/libfreetype.so.6
Try: zypper install -C "debuginfo(build-id)=6720cab1aaeba534efd6f572ca4e70ea86952d78"
Missing separate debuginfo for /usr/lib64/libEGL.so.1
Try: zypper install -C "debuginfo(build-id)=71bf908b5febbd4d03ab424af95714fec8c6bfc1"
Missing separate debuginfo for /usr/lib64/libxcb-shm.so.0
Try: zypper install -C "debuginfo(build-id)=8f8b3608615f913d6809f775cbdbb0a6e8825595"
Missing separate debuginfo for /usr/lib64/libxcb-render.so.0
Try: zypper install -C "debuginfo(build-id)=cca248e479f1a8664ea52bf6fca92149ad1ebc25"
Missing separate debuginfo for /usr/lib64/libXrender.so.1
Try: zypper install -C "debuginfo(build-id)=3f7f3baee4691ad03fd912713584b617d8c7cc14"
Missing separate debuginfo for /lib64/librt.so.1
Try: zypper install -C "debuginfo(build-id)=8f023124de2f61f08543a43e76b51d92a830300d"
Missing separate debuginfo for /usr/lib64/libXau.so.6
Try: zypper install -C "debuginfo(build-id)=c09982ac61d32c326e2a49595c119dcb5354f24c"
Missing separate debuginfo for /usr/lib64/libX11-xcb.so.1
Try: zypper install -C "debuginfo(build-id)=eaf1fb158a70511e3e078a38141fd545c667533b"
Missing separate debuginfo for /usr/lib64/libpulse.so.0
Try: zypper install -C "debuginfo(build-id)=d4f6da5778d2cd9e7f34c8a244f94ed928fe0392"
Missing separate debuginfo for /usr/lib64/libproxy.so.1
Try: zypper install -C "debuginfo(build-id)=7f939e8f74a74a62a2ecaf8a6576b82b8fe8e449"
Missing separate debuginfo for /usr/lib64/libssl.so.1.1
Try: zypper install -C "debuginfo(build-id)=1ebbd4607a3165f3d56d64090014c9bfe62b6c46"
Missing separate debuginfo for /usr/lib64/libcrypto.so.1.1
Try: zypper install -C "debuginfo(build-id)=0fc81ec33a187643e108c1dac7cd0ee3c71f4555"
Missing separate debuginfo for /usr/lib64/libGLX.so.0
Try: zypper install -C "debuginfo(build-id)=2b8fb33b8af5e1198a088ad447cbaef0067d4831"
Missing separate debuginfo for /usr/lib64/libGLdispatch.so.0
Try: zypper install -C "debuginfo(build-id)=f1a59a6edddb1ed73b83389ca4b407447050ed4d"
Missing separate debuginfo for /usr/lib64/libgraphite2.so.3
Try: zypper install -C "debuginfo(build-id)=84c805b1c0d83c1eb54ef2a6bd61f6af730ecedf"
Missing separate debuginfo for /usr/lib64/liblz4.so.1
Try: zypper install -C "debuginfo(build-id)=4473b17664a456ab9c269ad6b544673624f8be4b"
Missing separate debuginfo for /usr/lib64/libgcrypt.so.20
Try: zypper install -C "debuginfo(build-id)=bf0f199e3b25cc04925e80d5f491e6c523ad5a39"
Missing separate debuginfo for /usr/lib64/libicudata.so.suse64.2
Try: zypper install -C "debuginfo(build-id)=f4f01af306c930fb69deaa645384358ec656c9f9"
Missing separate debuginfo for /usr/lib64/libgmodule-2.0.so.0
Try: zypper install -C "debuginfo(build-id)=d03e37d518caf0dfc58bd4887d293f567976cae3"
Missing separate debuginfo for /usr/lib64/libmount.so.1
Try: zypper install -C "debuginfo(build-id)=98de071ae9f265d2cb622b6a4f3580caff6d6360"
Missing separate debuginfo for /lib64/libselinux.so.1
Try: zypper install -C "debuginfo(build-id)=bce40dd311b3dbb51778593d7160aa2083caffcd"
Missing separate debuginfo for /lib64/libresolv.so.2
Try: zypper install -C "debuginfo(build-id)=7dacee70165f624ef2fde4f77a72b6cb57980c51"
Missing separate debuginfo for /usr/lib64/libfribidi.so.0
Try: zypper install -C "debuginfo(build-id)=e635767c2f6cc7aac2d0f1967e480199e07c16dd"
Missing separate debuginfo for /usr/lib64/libthai.so.0
Try: zypper install -C "debuginfo(build-id)=9b5a574d118c30669966dc0edd495413d5d6bb2c"
Missing separate debuginfo for /usr/lib64/libexpat.so.1
Try: zypper install -C "debuginfo(build-id)=026bb37f8aec078a977a50f727e78a7d1ab03199"
Missing separate debuginfo for /usr/lib64/libuuid.so.1
Try: zypper install -C "debuginfo(build-id)=dd6671156314858222b7ad265239d723a7e4e25a"
Missing separate debuginfo for /usr/lib64/libbz2.so.1
Try: zypper install -C "debuginfo(build-id)=0eed6d08c1e4112540ba3d93dd98a29afcc693a7"
Missing separate debuginfo for /usr/lib64/pulseaudio/libpulsecommon-12.2.so
Try: zypper install -C "debuginfo(build-id)=a4390a973972f61e63896d6b22b760520c7da8b2"
Missing separate debuginfo for /usr/lib64/libmodman.so.1
Try: zypper install -C "debuginfo(build-id)=09cc90baa29639fe766e239e85b7185c1c45a410"
Missing separate debuginfo for /usr/lib64/libgpg-error.so.0
Try: zypper install -C "debuginfo(build-id)=b3299d3b14046c0298d2a0ca5c6998862881f6c3"
Missing separate debuginfo for /usr/lib64/libblkid.so.1
Try: zypper install -C "debuginfo(build-id)=24e074ae19bc648fa16884becfc3a36c76dfcb5e"
Missing separate debuginfo for /usr/lib64/libdatrie.so.1
Try: zypper install -C "debuginfo(build-id)=f0ff0a120c522753c9c4054c616d105695c95a68"
Missing separate debuginfo for /usr/lib64/libsndfile.so.1
Try: zypper install -C "debuginfo(build-id)=90d00e8a431738db40ee90fe0c891b9970145090"
Missing separate debuginfo for /usr/lib64/libFLAC.so.8
Try: zypper install -C "debuginfo(build-id)=4ae2876ff5d30bb26901b468009e3c2fa6b37cdd"
Missing separate debuginfo for /usr/lib64/libogg.so.0
Try: zypper install -C "debuginfo(build-id)=4d7a3584ad7d3ddca4078d1478825d2c81971772"
Missing separate debuginfo for /usr/lib64/libvorbis.so.0
Try: zypper install -C "debuginfo(build-id)=99a4b1b8b3b192eef3fe2e8e8ab19b4172d067a9"
Missing separate debuginfo for /usr/lib64/libvorbisenc.so.2
Try: zypper install -C "debuginfo(build-id)=7ed8a1c1a4d64e4e5dfaf4130f511d6b182ae3f3"

Program received signal SIGSEGV, Segmentation fault.
0x0000555555593c73 in QHash<QString, std::function<SlideEffect* ()> >::findNode(QString const&, unsigned int*) const [clone .constprop.0] ()
(gdb) 
```

**Comment by hillwoodroc** [comment]
```
(gdb) bt
#0  0x0000555555593c73 in QHash<QString, std::function<SlideEffect* ()> >::findNode(QString const&, unsigned int*) const [clone .constprop.0] ()
#1  0x000055555559215b in SlideEffect::Register(QString, std::function<SlideEffect* ()>) ()
#2  0x00005555555842a4 in global constructors keyed to 65535_0_bottomtoolbar.o.58034 ()
#3  0x00005555555ce175 in __libc_csu_init ()
#4  0x00007ffff7e17b5a in __libc_start_main () from /lib64/libc.so.6
#5  0x000055555559246a in _start ()
```

**Comment by hillwoodroc** [comment]
More dbug informations
#0  QHash<QString, std::function<SlideEffect* ()> >::findNode(QString const&, unsigned int*) const [clone .constprop.0] (akey=..., ahp=ahp@entry=0x0, 
    this=0x55555564fa00 <SlideEffect::effects>)
    at /usr/include/qt5/QtCore/qhash.h:933
#1  0x000055555559216b in QHash<QString, std::function<SlideEffect* ()> >::contains(QString const&) const (akey=..., this=<optimized out>)
    at /usr/include/qt5/QtCore/qhash.h:906
#2  SlideEffect::Register(QString, std::function<SlideEffect* ()>) (id=..., 
    c=...) at module/slideshow/slideeffect.cpp:59
#3  0x00005555555842b4 in _sub_I_65535_0.62381 ()
#4  0x00005555555ce2f5 in __libc_csu_init (argc=1, argv=0x7fffffffdf88, 
    envp=0x7fffffffdf98) at elf-init.c:88
#5  0x00007ffff7e15d9a in __libc_start_main () from /lib64/libc.so.6
#6  0x000055555559247a in _start () at ../sysdeps/x86_64/start.S:120

**Comment by dependon** [comment]
It's been a long time. It should be better now

**Comment by hillwoodroc** [comment]
Still can't work
https://github.com/linuxdeepin/deepin-image-viewer/issues/64
