### ISSUE TITLE
Segmentation fault on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/deepin-image-viewer#64]
version: 5.6.3.73

```
#0  0x00005555556051ae in QHash<QString, std::function<SlideEffect* ()> >::findNode(QString const&, unsigned int*) const (this=0x55555571a7d0 <SlideEffect::effects>, ahp=0x0, akey=...)
    at /usr/include/qt5/QtCore/qhash.h:945
#1  QHash<QString, std::function<SlideEffect* ()> >::contains(QString const&) const (
    this=0x55555571a7d0 <SlideEffect::effects>, akey=...)
    at /usr/include/qt5/QtCore/qhash.h:920
#2  SlideEffect::Register(QString, std::function<SlideEffect* ()>) (id=..., c=...)
    at module/slideshow/slideeffect.cpp:126
#3  0x00005555555bcf82 in SlideEffect::registerEffect<SlideEffect_Circle> (id=...)
    at module/slideshow/slideeffect.h:92
#4  register_effects () at module/slideshow/slideeffect_circle.cpp:69
#5  0x00005555555c150c in _sub_I_65535_0.0 ()
#6  0x0000555555651a7d in __libc_csu_init (argc=1, argv=0x7fffffffdd98, envp=0x7fffffffdda8)
    at elf-init.c:89
#7  0x00007ffff602bab1 in __libc_start_main () from /lib64/libc.so.6
#8  0x00005555555c6cbe in _start () at ../sysdeps/x86_64/start.S:120
```

**Comment by dependon** [comment]
oh,I think this bug I encountered this problem a few days ago, and the latest code should be repaired.thank you!

**Comment by hillwoodroc** [comment]
Confirm it fixed.
